version: "3.8"
services:

  db:
    image: postgres:15
    container_name: tech_blog_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5433:5432

  blog:
    image: tech_blog
    build:
      context: .
    container_name: tech_blog
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  postgresdata: