version: "3.8"
services:

  db:
    image: postgres:15
    container_name: tech_blog_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10

  blog:
    image: tech_blog
    build:
      context: .
    container_name: tech_blog
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure:3
    ports:
      - 8080:8080

volumes:
  postgresdata:
