"""update tables

Revision ID: 8b0fbef399e9
Revises: 02ef5e3b5a11
Create Date: 2024-09-18 13:57:30.524386

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b0fbef399e9"
down_revision: Union[str, None] = "02ef5e3b5a11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("comments_article_id_fkey", "comments", type_="foreignkey")
    op.create_foreign_key(
        None, "comments", "articles", ["article_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("complaints_article_id_fkey", "complaints", type_="foreignkey")
    op.create_foreign_key(
        None, "complaints", "articles", ["article_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("reviews_article_id_fkey", "reviews", type_="foreignkey")
    op.create_foreign_key(
        None, "reviews", "articles", ["article_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "reviews", type_="foreignkey")
    op.create_foreign_key(
        "reviews_article_id_fkey", "reviews", "articles", ["article_id"], ["id"]
    )
    op.drop_constraint(None, "complaints", type_="foreignkey")
    op.create_foreign_key(
        "complaints_article_id_fkey", "complaints", "articles", ["article_id"], ["id"]
    )
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.create_foreign_key(
        "comments_article_id_fkey", "comments", "articles", ["article_id"], ["id"]
    )
    # ### end Alembic commands ###
